### ISSUE TITLE
GameServer无法正常启动

### ISSUE THREAD

**Issue by guozanhua** [cloudfreexiao/AntServer#2]
get最新了版本，启动服务器，gameserver报以下问题
[:0000001f] LAUNCH snlua hubd node1
[:0000000d] lua call [c to :d : 10 msgsz = 26] error : [31mskynet/lualib/skynet.lua:642: skynet/lualib/skynet.lua:184: service/common/redis_slave.lua:144: attempt to index a nil value (upvalue 'db')
stack traceback:
	service/common/redis_slave.lua:144: in local 'f'
	service/common/redis_slave.lua:155: in upvalue 'f'
	skynet/lualib/skynet.lua:141: in function <skynet/lualib/skynet.lua:113>
stack traceback:
	[C]: in function 'assert'
	skynet/lualib/skynet.lua:642: in function 'skynet.dispatch_message'[0m
[:0000000c] lua call [d to :c : 10 msgsz = 0] error : [31mskynet/lualib/skynet.lua:642: skynet/lualib/skynet.lua:184: skynet/lualib/skynet.lua:384: call failed
stack traceback:
	[C]: in function 'error'
	skynet/lualib/skynet.lua:384: in upvalue 'yield_call'
	skynet/lualib/skynet.lua:401: in function 'skynet.call'
	(...tail calls...)
	service/common/redispool.lua:191: in upvalue 'f'
	skynet/lualib/skynet.lua:141: in function <skynet/lualib/skynet.lua:113>
stack traceback:
	[C]: in function 'assert'
	skynet/lualib/skynet.lua:642: in function 'skynet.dispatch_message'[0m
[:0000001f] init service failed: skynet/lualib/skynet.lua:384: call failed
stack traceback:
	[C]: in function 'error'
	skynet/lualib/skynet.lua:384: in upvalue 'yield_call'
	skynet/lualib/skynet.lua:401: in function 'skynet.call'
	(...tail calls...)
	service/game/hub/index.lua:23: in upvalue 'init_agent_uin'
	service/game/hub/index.lua:29: in function 'hub.index.init'
	service/game/hubd.lua:146: in local 'start'
	skynet/lualib/skynet.lua:746: in function <skynet/lualib/skynet.lua:743>
	[C]: in function 'xpcall'
	skynet/lualib/skynet.lua:750: in function 'skynet.pcall'
	skynet/lualib/skynet.lua:754: in function 'skynet.init_service'
	skynet/lualib/skynet.lua:767: in upvalue 'f'
	skynet/lualib/skynet.lua:114: in function <skynet/lualib/skynet.lua:113>
[:0000001f] KILL self
[:00000008] init service failed: skynet/lualib/skynet.lua:653: skynet/service/service_mgr.lua:25: skynet/lualib/skynet.lua:384: call failed
stack traceback:
	[C]: in function 'assert'
	skynet/lualib/skynet.lua:653: in function 'skynet.uniqueservice'
	service/game/main_game.lua:10: in upvalue 'start_gated'
	service/game/main_game.lua:83: in local 'start'
	skynet/lualib/skynet.lua:746: in function <skynet/lualib/skynet.lua:743>
	[C]: in function 'xpcall'
	skynet/lualib/skynet.lua:750: in function 'skynet.pcall'
	skynet/lualib/skynet.lua:754: in function 'skynet.init_service'
	skynet/lualib/skynet.lua:767: in upvalue 'f'
	skynet/lualib/skynet.lua:114: in function <skynet/lualib/skynet.lua:113>
[:00000008] KILL self
[:00000002] KILL self

**Comment by cloudfreexiao** [comment]
你检查下 redis 的配置 是否正确
[端口](https://github.com/cloudfreexiao/AntServer/blob/master/common/setting/settings_template.lua#L102)
 链接不上 应该有 类似日志:
```lua
[error] ---redis connect error---
```

**Comment by guozanhua** [comment]
redis的端口是16379，调整后服务器启动正常了，但是服务端没有login.proto, unity_client链接还是有问题

**Comment by cloudfreexiao** [comment]
登录是 走 http

**Comment by guozanhua** [comment]
> 登录是 走 http

public class TestLoginTcp
	{
		private LoginClient _client;
		private readonly string _protocol = "tcp";

		public TestLoginTcp(string p)
		{
			_protocol = p;
		}

		public void Run(Action<int, AuthPackageResp> loginCallBack)
		{
			_client = new LoginClient();

			var req = new AuthPackageReq {openId = "test_cloudfreexiao_001", sdk = "2", protocol = _protocol};

			_client.Connect("127.0.0.1", 15111, req, loginCallBack);
		}

		public void DisConnect()
		{
			_client.Disconnect();
		}
	}

======================
代码是走tcp的协议，这个接口是和loginserver通讯不，看代码的流程，通过loginserver登陆，登陆成功后，链接gate server，gateserver链接成功后会切换到game server，没看出来login是走http的协议。
